-- MySQL Script generated by MySQL Workbench
-- 08/06/20 12:14:11
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sigai
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sigai` ;

-- -----------------------------------------------------
-- Schema sigai
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sigai` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `sigai` ;

-- -----------------------------------------------------
-- Table `empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `empresa` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `empresa` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  `abreviacao` VARCHAR(45) NULL,
  `endereco` VARCHAR(255) NULL,
  `cep` VARCHAR(45) NULL,
  `cnpj` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `email` VARCHAR(255) NULL,
  `site` VARCHAR(255) NULL,
  `figura` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `setor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `setor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `setor` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  `abreviacao` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `usuario` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `setor_id` INT UNSIGNED NOT NULL,
  `matricula` VARCHAR(45) NULL,
  `cargo` VARCHAR(45) NULL,
  `nome` VARCHAR(255) NOT NULL,
  `usuario` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `acesso` INT NULL,
  `cadastro` DATE NULL,
  `imagem` VARCHAR(255) NULL,
  `status` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE UNIQUE INDEX `usuario_UNIQUE` ON `usuario` (`usuario` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `email_UNIQUE` ON `usuario` (`email` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `chamado_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chamado_status` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `chamado_status` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `chamado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chamado` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `chamado` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `setor_id` INT UNSIGNED NOT NULL,
  `usuario_id` INT UNSIGNED NOT NULL,
  `status_id` INT UNSIGNED NOT NULL,
  `assunto` VARCHAR(255) NULL,
  `data` DATETIME NULL,
  `anexo` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `chamado_historico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chamado_historico` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `chamado_historico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `chamado_id` INT UNSIGNED NOT NULL,
  `status_id` INT UNSIGNED NOT NULL,
  `usuario_id` INT UNSIGNED NOT NULL,
  `data` DATETIME NULL,
  `descricao` TEXT NULL,
  `anexo` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Data for table `empresa`
-- -----------------------------------------------------
START TRANSACTION;
USE `sigai`;
INSERT INTO `empresa` (`id`, `nome`, `abreviacao`, `endereco`, `cep`, `cnpj`, `telefone`, `email`, `site`, `figura`) VALUES (1, 'Secretaria Municipal de Meio Ambiente', 'SEMMA', 'R. Quincas Nascimento - Saudade I, Castanhal - PA', ' 68741-040', '05.121.991/0001-84', '(91) 3711-5959', 'semma@castanhal.pa.gov.br', NULL, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `setor`
-- -----------------------------------------------------
START TRANSACTION;
USE `sigai`;
INSERT INTO `setor` (`id`, `nome`, `abreviacao`) VALUES (1, 'Coordenação de Controle Ambiental', 'CCA');
INSERT INTO `setor` (`id`, `nome`, `abreviacao`) VALUES (2, 'Coordenadoria de Conservação de Áreas Verdes', 'CCAV');
INSERT INTO `setor` (`id`, `nome`, `abreviacao`) VALUES (3, 'Coordenadoria Administrativa e Financeira', 'COAF');
INSERT INTO `setor` (`id`, `nome`, `abreviacao`) VALUES (4, 'Coordenadoria de Gestão de Agrossilvipastoris', 'CGA');
INSERT INTO `setor` (`id`, `nome`, `abreviacao`) VALUES (5, 'Coordenadoria de Fiscalização Ambiental', 'COFISC');
INSERT INTO `setor` (`id`, `nome`, `abreviacao`) VALUES (6, 'Assessoria Jurídica', 'ASJUR');
INSERT INTO `setor` (`id`, `nome`, `abreviacao`) VALUES (7, 'Assessoria Técnica', 'ASTEC');
INSERT INTO `setor` (`id`, `nome`, `abreviacao`) VALUES (8, 'Gabinete da Secretária', 'GAB-SEC');
INSERT INTO `setor` (`id`, `nome`, `abreviacao`) VALUES (9, 'Arquivos da Secretária', 'AR-SEC');
INSERT INTO `setor` (`id`, `nome`, `abreviacao`) VALUES (10, 'Protocolo da Secretária', 'PRO-SEC');

COMMIT;


-- -----------------------------------------------------
-- Data for table `usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `sigai`;
INSERT INTO `usuario` (`id`, `setor_id`, `matricula`, `cargo`, `nome`, `usuario`, `email`, `senha`, `acesso`, `cadastro`, `imagem`, `status`) VALUES (1, 1, '1.137/20', 'Coordenador', 'Joab Torres Alencar', 'joab.alencar', 'joabtorres1508@gmail.com', '96560262', 10, '2020-08-06', NULL, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `chamado_status`
-- -----------------------------------------------------
START TRANSACTION;
USE `sigai`;
INSERT INTO `chamado_status` (`id`, `nome`) VALUES (1, 'Aguardando o Suporte');
INSERT INTO `chamado_status` (`id`, `nome`) VALUES (2, 'Em Andamento');
INSERT INTO `chamado_status` (`id`, `nome`) VALUES (3, 'Cancelado');
INSERT INTO `chamado_status` (`id`, `nome`) VALUES (4, 'Finalizado');

COMMIT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
